---
title: "Resultado-electoral"
author: "Jair Alva"
date: "12/1/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(readr)
library(rio)
library(tidyverse)
library(sf)
library(tmap)
```

```{r}
segunda_vuelta <- import("https://github.com/JairAlva/Data-Libre/blob/main/Elecciones%20presidenciales%202021/Segunda%20vuelta/Resultados_2d_vuelta.dta?raw=true")
```

# Analicemos las provincias de Ancash

### Resultado para distritos de Huaraz
```{r}
distritos_ancash <- segunda_vuelta |> filter(DEPARTAMENTO == "ANCASH") |>  
  mutate_at(vars(N_CVAS:VOTOS_VN), ~replace_na(.,0)) |> 
  group_by(UBIGEO, DISTRITO, PROVINCIA) |> 
  summarise(across(N_CVAS:VOTOS_VN, sum)) |> 
  mutate(votos_validos = N_CVAS - VOTOS_VB - VOTOS_VN,
         prc_Peru_Libre = VOTOS_P1/votos_validos*100,
         prc_Fuerza_popular = VOTOS_P2/votos_validos*100,
         prc_participacion = votos_validos/N_ELEC_HABIL*100) |> 
  select(UBIGEO, DISTRITO, PROVINCIA, prc_Peru_Libre, prc_Fuerza_popular,
         prc_participacion) |> 
  rename(Provincia = PROVINCIA) |> 
  mutate(Provincia = str_to_title(Provincia)) |> 
  ungroup()
```

### Filtro de las provincias
```{r}
distritos_ancash |>  
  select(Provincia) |> 
  mutate(Provincia = str_to_title(Provincia)) |> 
  distinct() |> 
  arrange(Provincia)
```

### Equiparamos los ubigeos
```{r}
ubigeos = read_csv("https://raw.githubusercontent.com/JairAlva/Data-Libre/main/Ubigeos/TB_UBIGEOS.csv")

ubigeos = ubigeos |>  select(ubigeo_reniec, ubigeo_inei, distrito)

distritos_ancash = distritos_ancash |>  
  left_join(ubigeos, by = c("UBIGEO" = "ubigeo_reniec")) |>  
  mutate(distrito = str_to_title(distrito))
```


## Participación electoral
```{r}
distritos_ancash |> 
  filter(Provincia == "Huaraz") |> 
  ggplot() + geom_col(aes(x=reorder(distrito, +prc_participacion), 
                          y= prc_participacion), fill = "pink") +
  theme_classic() +
  ylab("Porcentaje de participación") + xlab("Distrito") +
  coord_flip()
```

## Mapa de la provincia de Huaraz
```{r}
distritos_shp = st_read("https://raw.githubusercontent.com/JairAlva/Data-Libre/main/Peru_maps/DISTRITOS.json")
```

### Mapa de Huaraz
```{r}
huaraz_shp = distritos_shp |> 
  filter(PROVINCIA == "HUARAZ") |> 
  left_join(distritos_huaraz, by = c("IDDIST" = "ubigeo_inei")) |> 
  select(!UBIGEO & !distrito) |> 
  mutate(DISTRITO = str_to_title(DISTRITO), 
         nombre = str_c(DISTRITO , " ", round(prc_participacion,2), "%"))
```

### Mapa de participación
```{r}
participacion = tm_shape(huaraz_shp) +
  tm_polygons("prc_participacion", id= "nombre", border.alpha=0.3, 
              alpha=0.6, legend.show = F) #, palette="Reds"

participacion
tmap_mode("view")
tmap_last()
#tmap_save(participacion, filename = "participacion.html")
```

### Ahora hagamos un mapa de voto hacia Castillo